### ISSUE TITLE
Gradient fill causes crash.

### ISSUE THREAD

**Issue by ReubenM** [hacktoon/ink2canvas#4]
The readme said gradients should be supported, so I figured I should post error caused by gradient fill.

Traceback (most recent call last):
  File "canvas.py", line 427, in <module>
    ink.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 207, in affect
    self.effect()
  File "canvas.py", line 423, in effect
    self.drawG(ctx, svg)
  File "canvas.py", line 410, in drawG
    getattr(self, method)(ctx, child)
  File "canvas.py", line 410, in drawG
    getattr(self, method)(ctx, child)
  File "canvas.py", line 369, in drawPath
    self.drawAbstractShape(ctx, node, self.drawPathHelper, [ctx, path])
  File "canvas.py", line 230, in drawAbstractShape
    self.setStyle(ctx, node)
  File "canvas.py", line 223, in setStyle
    getattr(ctx, method)(style[key])
  File "canvas.py", line 133, in setFill
    self.write("%s.fillStyle = %s;" % (self.obj, self.fillHelper(value, a)))
  File "canvas.py", line 122, in fillHelper
    return self.getGradient(rgb[5:-1])
AttributeError: Canvas instance has no attribute 'getGradient'

**Comment by CMiksche** [comment]
@hacktoon

After working with some SVGs, this error seems to be open. It's more than 8 years since this error was opened - can you give a little update on the current status?

Maybe someone would like to contribute to this error / feature ...

(I would be happy if i could use that functionality ...)

**Comment by hacktoon** [comment]
I'm sorry. I'm too busy to work on this project right now.

**Comment by camouflagedcontribution** [comment]
Seems to be the only open issue in an extraordinarily stable utility. Tried a bunch of different shapes and gradients successfully with win 10 + inkscape 0.92 portable edition. Anybody got steps to reproduce these errors?
